name: Manual

on:
  workflow_dispatch:
    inputs:
      version:
        description: Version
        type: string
        required: true
      environment:
        description: Environment
        type: string
        required: true
      test:
        description: Test (1)
        type: string
        required: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Testing (1)
        run: |
          echo "Log level: $VERSION"
          echo "Environment: $ENVIRONMENT"
          echo "Test: $TEST"
        env:
          VERSION: ${{ inputs.version }}
          ENVIRONMENT: ${{ inputs.environment }}
          TEST: ${{ inputs.test }}
