name: PR commented

on:
  issue_comment:
    types: [created]

jobs:
  my_test:
    runs-on: ubuntu-latest
    if: ${{ github.event.issue.pull_request }}
    steps:
      - run: echo "Created comment - Step 1"
