# name: test2

# on:
#   issue_comment:
#     types: [created]

# jobs:
#   create_comment:
#     runs-on: ubuntu-latest
#     if: ${{ github.event.issue.pull_request }}
#     steps:
#       - run: echo "Create comment - Step 1"
