name: PR commented

on:
  issue_comment:
    types: [created]

jobs:
  my_test_on_comment:
    runs-on: ubuntu-latest
    if: ${{ github.event.issue.pull_request }}
    steps:
      # - run: echo "${{ toJSON(github.event) }}"
      - name: Parse comment
        id: parseComment
        env:
          COMMENT_TEXT: ${{ github.event.comment.body }}
        run: |
          COMMAND=${COMMENT_TEXT:0:5} 

          if [[ $COMMAND == "/e2e " ]]
          then
            IFS=" "
            read -ra COMMENT_ARRAY <<< "$COMMENT_TEXT"
            ENVIRONMENT=${COMMENT_ARRAY[1]}
            echo "CAN_EXECUTE_TEST=true" >> $GITHUB_OUTPUT
            echo "ENVIRONMENT=${ENVIRONMENT}" >> $GITHUB_OUTPUT
          else
            echo "CAN_EXECUTE_TEST=false" >> $GITHUB_OUTPUT
          fi
      - name: Execute test
        if: steps.parseComment.outputs.CAN_EXECUTE_TEST == 'TRUE'
        env:
          ENVIRONMENT: ${{ steps.parseComment.outputs.ENVIRONMENT }}
        run: echo "Execute in ${ENVIRONMENT}"
      - name: Create comment
        id: createComment
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.issue.number }}
          GIT_REPOSITORY: ${{ github.repository }}
        run: |
          gh pr comment $PR_NUMBER --repo $GIT_REPOSITORY --body "Created by Github *action*"
          
