name: PR commented

on:
  issue_comment:
    types: [created]

jobs:
  my_test_on_comment:
    runs-on: ubuntu-latest
    if: ${{ github.event.issue.pull_request }}
    steps:
      - run: echo "Created comment on PR $PR_NUMBER"
        env:
          PR_NUMBER: ${{ github.event.issue.number }}
      - run: echo "${{ toJSON(github.event) }}"
