name: PR commented

on:
  issue_comment:
    types: [created]

jobs:
  my_test_on_comment:
    runs-on: ubuntu-latest
    if: ${{ github.event.issue.pull_request }}
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GH_REPO: ${{ github.repository }}
      PR_NUMBER: ${{ github.event.issue.number }}
      USER_NAME: ${{ github.event.comment.user.login }}
    steps:
      - run: echo "${{ toJSON(github.event) }}"

      - name: Parse comment
        id: parseComment
        env:
          COMMENT_TEXT: ${{ github.event.comment.body }}
        run: |
          IFS=" "
          read -ra COMMENT_ARRAY <<< "$COMMENT_TEXT"

          COMMAND=${COMMENT_ARRAY[0]} 
          PARAMETER=${COMMENT_ARRAY[1]}

          if [[ $COMMAND == "/e2e" && $PARAMETER != "" ]]
          then
            if [[ $PARAMETER == "skip" ]]
            then
              echo "ACTION=SKIP_TEST" >> $GITHUB_OUTPUT
            else
              echo "ACTION=RUN_TEST" >> $GITHUB_OUTPUT
              echo "ENVIRONMENT=${PARAMETER}" >> $GITHUB_OUTPUT
            fi
          else
            echo "ACTION=NOTHING" >> $GITHUB_OUTPUT
          fi

      - name: Execute test
        if: steps.parseComment.outputs.ACTION == 'RUN_TEST'
        env:
          ENVIRONMENT: ${{ steps.parseComment.outputs.ENVIRONMENT }}
        run: echo "Run tests in ${ENVIRONMENT}"

      - name: Comment with results
        if: steps.parseComment.outputs.ACTION == 'RUN_TEST'
        env:
          ENVIRONMENT: ${{ steps.parseComment.outputs.ENVIRONMENT }}
        run: |
          gh pr comment $PR_NUMBER --body "Tests ran by @$USER_NAME in $ENVIRONMENT"

      - name: Comment tests skkiped
        if: steps.parseComment.outputs.ACTION == 'SKIP_TEST'
        run: |
          gh pr comment $PR_NUMBER --body "Tests skipped by @$USER_NAME"

      - name: Get SHA of PR
        if: steps.parseComment.outputs.ACTION != 'NOTHING'
        id: getSHA
        env:
          GH_API_HEADERS: "-H \"Accept: application/vnd.github+json\" -H \"X-GitHub-Api-Version: 2022-11-28\""
        run: |
          PR_JSON=$(gh api -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" /repos/$GH_REPO/pulls/$PR_NUMBER)
          SHA=$(echo $PR_JSON | jq -r .head.sha)
          echo "SHA=$SHA" >> $GITHUB_OUTPUT

      - name: Mark PR as checked
        if: steps.parseComment.outputs.ACTION != 'NOTHING'
        env:
          SHA: ${{ steps.getSHA.outputs.SHA  }}
        run: |
          gh api \
            --method POST /repos/$GH_REPO/statuses/$SHA \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            -f state='success' \
            -f context='e2e_check' \
            -f description='End to end testing'
