name: PR created or changed

on:
  pull_request:
    branches: [ main, master ]

permissions:
  statuses: write

jobs:
  my_build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ toJSON(github.event) }}"
      - name: "Build"
        run: echo "Ok"
