name: test1

on:
  workflow_dispatch:
    inputs:
      test:
        description: 'Test'
        required: false
        type: boolean
  pull_request:
    branches: [ main, master ]

jobs:
  hello_world:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World!"
      # - run: docker --version
      # - run: cd /home/runner/work/t-ga/t-ga;ls -la
      # - run: printenv
      - run: echo ${{ toJSON(github) }}

  # raise_error:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - run: exit 1
